default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  adapter: postgresql
  host: localhost
  port: 5432
  user: <%= ENV['POSTGRES_USER_KEY'] %>
  password: <%= ENV['POSTGRES_PASSWORD_KEY'] %>
  database: <%= ENV['POSTGRES_DATABASE_KEY'] %>
